project: 
  type: website
  # output-dir: docs

website: 
  page-navigation: true
  title: "Workflows Guidebook" 
  site-url: "https://nmfs-ost.github.io/workflows-guidebook/" 
  repo-url: "https://github.com/nmfs-ost/workflows-guidebook"
  repo-actions: [edit, source, issue]
  # favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nmfs-ost.github.io/workflows-guidebook/
        text: "Guidebook website"
      - icon: github
        href: https://github.com/nmfs-ost/workflows-guidebook
        text: "Guidebook Github"

    search: true
    collapse-level: 1
    contents:
    - href: index.qmd
      text: Home
    - section: "Team"
      # style: "docked"
      contents:
      - href: content/team/who.qmd
        text: Who
      - href: content/team/what.qmd
        text: What
      - href: content/team/when.qmd
        text: When
      - href: content/team/where.qmd
        text: Where
      - href: content/why.qmd
        text: Why
    - section: "Steering Committee"
      # style: "docked"
      contents:
      - href: content/steering_committee/how.qmd
        text: How is the Steering Committee run?
      - href: content/steering_committee/what.qmd
        text: What is their role?
      - href: content/steering_committee/who.qmd
        text: Who is the steering committee?
      - href: content/steering_committee/when_where.qmd
        text: When and where do they meet?
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto
